import "@/app/globals.css";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import QueryClientProviderWrapper from "@/providers/query_provider_wrapper";
import {
  sirwan_light,
  sirwan_bold,
  sirwan_meduim,
  sirwan_reguler,
} from "@/public/fonts";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: {
    default: "Bom Bena",
    template: "%s - Bom Bena",
  },
  description: "Bom Bena is a modern  System Generated by Avana Soft Company",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <QueryClientProviderWrapper>
        <SidebarProvider className="rounded-l-2xl">
          <AppSidebar side="right" />
          <ThemeProvider
            attribute="class"
            defaultTheme="ligth"
            disableTransitionOnChange
          >
            <main className="w-full px-2 sm:px-4 py-2">
              <div className="w-full flex md:hidden   justify-between items-center">
                <SidebarTrigger />
                {/* <ToggleMode /> */}
              </div>
              <div
                className={`w-full my-2 ${sirwan_reguler.variable}  ${sirwan_bold.variable} ${sirwan_light.variable} ${sirwan_meduim.variable} font-sirwan-reguler `}
              >
                <NuqsAdapter>{children}</NuqsAdapter>
              </div>
              <Toaster
                dir="rtl"
                richColors
                toastOptions={{
                  className: "font-sirwan-reguler",
                }}
              />
            </main>
          </ThemeProvider>
        </SidebarProvider>
      </QueryClientProviderWrapper>
    </div>
  );
}
