import type { Metadata } from "next";
import "./globals.css";
import {
  sirwan_light,
  sirwan_bold,
  sirwan_meduim,
  sirwan_reguler,
} from "@/public/fonts";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: {
    default: "Childrean Aboard Dashboard",
    template: "%s - Childrean Aboard Dashboard",
  },
  description:
    "Childrean Aboard Dashboard is a modern  System Generated by Avana Soft Company",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning dir="rtl">
      <body
        className={cn(
          ` ${sirwan_light.variable} ${sirwan_reguler.variable} ${sirwan_meduim.variable} ${sirwan_bold.variable} font-sirwan-reguler debug-screens`
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster
          dir="rtl"
          richColors
          toastOptions={{
            className: "font-sirwan-reguler",
          }}
        />
      </body>
    </html>
  );
}
